require("lsp.luals")
require("lsp.svelte")
require("lsp.ts_ls")
require("lsp.tailwindcss")
require("lsp.postgrestools")
require("lsp.css")
require("lsp.zig")
-- require("lsp.cmake")
require("lsp.neo_cmake")
require("lsp.clangd")
require("lsp.pyright")
require("lsp.tinymist")
require("lsp.ltex")
require("lsp.rust")

vim.lsp.enable("lua_ls")
vim.lsp.enable("ts_ls")
vim.lsp.enable("gopls")
vim.lsp.enable("svelte-language-server")
vim.lsp.enable("tailwindcss-language-server")
vim.lsp.enable("dockerfile-language-server")
vim.lsp.enable("postgrestools")
vim.lsp.enable("cssls")
vim.lsp.enable("zls")
-- vim.lsp.enable("cmake-language-server")
vim.lsp.enable("neocmakelsp")
vim.lsp.enable("clangd")
vim.lsp.enable("pyright-langserver")
-- vim.lsp.enable("pylyzer")
vim.lsp.enable("tinymist")
vim.lsp.enable("ltex-ls")
vim.lsp.enable("rust-analyzer")
